name: PiliPlus
description: A new Flutter project.
publish_to: "none"

version: 1.1.5+1

environment:
  sdk: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  get:
    git:
      url: https://github.com/bggRGjQaUbCoE/getx.git 
      ref: version_4.7.2
  dio: ^5.7.0
  cookie_jar: ^4.0.8
  connectivity_plus: ^7.0.0
  dio_http2_adapter: ^2.5.3
  cached_network_image: ^3.4.1
  saver_gallery: ^4.1.0
  pretty_qr_code: ^3.3.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^12.1.0
  permission_handler_apple: ^9.4.7
  permission_handler_android: ^13.0.1
  permission_handler_platform_interface: ^4.3.0
  share_plus: ^12.0.0
  flutter_inappwebview: ^6.1.5
  extended_nested_scroll_view:
    git:
      url: https://github.com/bggRGjQaUbCoE/extended_nested_scroll_view.git 
      ref: mod
  font_awesome_flutter: 10.9.0
  material_design_icons_flutter:
    git:
      url: https://github.com/bggRGjQaUbCoE/material_design_icons_flutter.git 
      ref: const
  flutter_smart_dialog: ^4.9.8+5
  crypto: ^3.0.6
  encrypt: ^5.0.3
  media_kit: 1.1.11
  media_kit_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: media_kit_video
      ref: version_1.2.5
  media_kit_libs_video: 1.0.5
  audio_service: ^0.18.15
  audio_session: ^0.2.2
  flutter_volume_controller: ^1.3.3
  wakelock_plus: ^1.2.8
  auto_orientation:
    git:
      url: https://github.com/bggRGjQaUbCoE/auto_orientation.git 
      ref: master
  protobuf: ^6.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  easy_debounce: ^2.0.3
  flutter_displaymode: ^0.7.0
  app_links: ^7.0.0
  canvas_danmaku:
    git:
      url: https://github.com/bggRGjQaUbCoE/canvas_danmaku.git 
      ref: main
  image_picker: ^1.1.2
  intl: ^0.20.2
  archive: ^4.0.0
  flutter_svg: ^2.0.14
  image_cropper: ^11.0.0
  brotli: ^0.6.0
  expandable: ^5.0.1
  flex_seed_scheme: ^4.0.1
  live_photo_maker: ^0.0.6
  fl_chart: ^1.0.0
  synchronized: ^3.3.0
  webdav_client:
    git:
      url: https://github.com/wgh136/webdav_client.git 
      ref: main
  re_highlight: ^0.0.3
  flutter_sortable_wrap:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_sortable_wrap.git 
      ref: master
  web_socket_channel: ^3.0.3
  window_manager:
    git:
      url: https://github.com/bggRGjQaUbCoE/window_manager.git 
      path: packages/window_manager
      ref: main
  tray_manager: ^0.5.1
  file_picker:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_file_picker.git 
      ref: mod
  super_sliver_list:
    git:
      url: https://github.com/bggRGjQaUbCoE/super_sliver_list.git 
      ref: mod
  dlna_dart: ^0.1.0
  battery_plus: ^7.0.0
  vector_math: any
  fixnum: any
  json_annotation: any
  stream_transform: any
  screen_brightness_platform_interface: any
  mime: any
  path: any
  collection: any
  material_color_utilities: any
  flutter_cache_manager: any
  http2: any
  screen_retriever: any
  characters: any

dependency_overrides:
  screen_brightness_ios: ^2.1.2
  screen_brightness_android: ^2.1.3
  screen_brightness_platform_interface: ^2.1.0
  path: ^1.9.1
  mime: ^2.0.0
  rxdart: ^0.28.0
  media_kit:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: media_kit
      ref: version_1.2.5
  media_kit_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: media_kit_video
      ref: version_1.2.5
  media_kit_libs_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: libs/universal/media_kit_libs_video
      ref: version_1.2.5
  media_kit_native_event_loop:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: media_kit_native_event_loop
      ref: version_1.2.5
  media_kit_libs_android_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: libs/android/media_kit_libs_android_video
      ref: version_1.2.5
  media_kit_libs_windows_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git 
      path: libs/windows/media_kit_libs_windows_video
      ref: version_1.2.5
  font_awesome_flutter: 10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0          # ← 唯一改动在这里
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.10.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo/logo_2.png
  image_path_android: assets/images/logo/logo_2.png
  image_path_ios: assets/images/logo/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo/logo_2.png
  adaptive_icon_monochrome: assets/images/logo/logo_2.png
  macos:
    generate: true
    image_path: assets/images/logo/logo.png

flutter_native_splash:
  android_12:
    color: "#ffffff"
    color_dark: "#212121"
  color: "#ffffff"
  color_dark: "#212121"
  image: assets/images/logo/logo_2.png
  image_dark: assets/images/logo/logo_2.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/lv/
    - assets/images/logo/
    - assets/images/live/
    - assets/images/video/
    - assets/images/paycoins/
    - assets/shaders/
  fonts:
    - family: digital_id_num
      fonts:
        - asset: assets/fonts/digital_id_num.ttf
    - family: custom_icon
      fonts:
        - asset: assets/fonts/custom_icon.ttf
